# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
